export { default as DesignPattern } from './DesignPattern'
export { default as DPOverview1 } from './DPOverview1'
export { default as DPOverview2 } from './DPOverview2'
export { default as DPOverview3 } from './DPOverview3'
export { default as DPOopOverview } from './DPOopOverview'
export { default as SRP } from './SRP'
export { default as OCP } from './OCP'